# Generated by Django 4.1.2 on 2022-10-27 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Main_Img', models.ImageField(default='', upload_to='images')),
                ('added_by_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('CompletionStatus', models.BooleanField(verbose_name='Completion Status')),
                ('daysgiven', models.IntegerField()),
                ('ToDoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todolist', verbose_name='To Do List')),
            ],
        ),
    ]
