# Generated by Django 4.0.4 on 2022-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolist_listadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='CompletionStatus',
            field=models.BooleanField(default=False, verbose_name='Completion Status'),
        ),
    ]
