# Generated by Django 4.1.2 on 2022-11-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_agent_agentadmin'),
        ('todoapp', '0003_todolist_completionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='listagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listagent', to='accounts.agent'),
        ),
    ]
