# Generated by Django 4.0.4 on 2022-10-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('CompletionStatus', models.BooleanField()),
                ('daysgiven', models.IntegerField()),
                ('ToDoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TODO.todolist', verbose_name='To Do List')),
            ],
        ),
    ]
