# Generated by Django 4.0.4 on 2022-10-09 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='added_by_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='CompletionStatus',
            field=models.BooleanField(verbose_name='Completion Status'),
        ),
    ]
