# Generated by Django 4.0.4 on 2022-10-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_todolist_added_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='Main_Img',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/'),
        ),
    ]
