# Generated by Django 4.0.4 on 2022-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0006_alter_todolist_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Main_Img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
