# Generated by Django 4.1.2 on 2022-10-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
