# Generated by Django 4.1.2 on 2022-10-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
