# Generated by Django 4.1.2 on 2022-11-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_todolist_listadmin_alter_todolist_listagent'),
        ('accounts', '0013_remove_admin_is_admin_remove_agent_is_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agentadmin',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='useracc',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='agent',
        ),
    ]
